config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  
  resources :lists do
    delete '/clear_items', to: 'lists#clear_items'
    resources :items
  end
  
  resources :notes, only: [:index, :show, :new, :create, :update, :destroy]
  
  post '/update_ranks', to: 'ranking#update_all'
end

app/models/list.rb
class List < ApplicationRecord
  include Rankable

  has_many :items, dependent: :destroy
  belongs_to :user  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]
  before_action :authenticate_user!

  def index
    @lists = List.where(user: current_user).ordered_by_rank
    render partial: 'lists/lists', locals: { lists: @lists }
  end

  def show
    user_not_authorized if @list.user != current_user
  end

  def destroy
    if @list.destroy
      render turbo_stream: turbo_stream.remove(@list)
    end
  end

  def clear_items
    @list = List.find(params[:list_id])
    
    if @list.items.destroy_all
      render turbo_stream: [
        turbo_stream.replace(:items, partial: 'items/items', locals: { items: nil }),
        turbo_stream.update(:items_count, 0)
      ]
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list.html.erb
<div id=<%= dom_id(list) %> class="group flex justify-between bg-white rounded-lg py-3 px-5 mb-2" data-sortable-target="item">
  <%= link_to list_path(list) do %>
    <%= list.name %>
  <% end %>
  <%= button_to list_path(list), method: :delete, form: {data: {turbo_confirm: 'Are you sure ?'}}, class: 'hidden group-hover:block' do %>
    <i class="fa-solid fa-trash text-gray-600"></i>
  <% end %>
</div>

app/views/lists/_lists.html.erb
<%= turbo_frame_tag "lists" do %>
  <div data-controller="sortable" data-sortable-class-value="List">
    <%= render partial: 'lists/list', collection: lists %>
  </div>
<% end %>

app/views/lists/show.html.erb
<%= render 'shared/back_home' %>

<div class="flex items-center">
  <h2><%= @list.name %></h2>
  <div id="items_count" class="flex justify-center items-center text-xs h-5 w-5 bg-blue-300 rounded-full ml-1"><%= @list.items.not_done.count %></div>
</div>

<%= render partial: 'items/add_item_button', locals: { list: @list } %>

<%= turbo_frame_tag "items", src: list_items_path(@list), loading: 'lazy' do %>
  <div>
    <i class="fas fa-spinner fa-spin fa-2xl"></i>
    <span>Loading items...</span>
  </div>
<% end %>

<% if @list.items.present? %>
  <%= link_to 'Clear list', list_clear_items_path(@list), data: { turbo_method: :delete }, class: 'block mt-3' %>
<% end %>