config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  
  resources :lists do
    delete '/clear_items', to: 'lists#clear_items'
    resources :items
  end
  
  resources :notes, only: [:index, :show, :new, :create, :update, :destroy]
  
  post '/update_ranks', to: 'ranking#update_all'
end

app/models/note.rb
class Note < ApplicationRecord
  include Rankable

  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  def index
    @notes = Note.where(user: current_user).ordered_by_rank
    render partial: 'notes/notes', locals: { notes: @notes }
  end

  def show
    user_not_authorized if @note.user != current_user
  end

  def new; end

  def create
    @note = Note.new(note_params)
    @note.user = current_user

    if @note.save
      redirect_to @note
    end
  end

  def update
    if @note.update(note_params)
      render turbo_stream: [
        turbo_stream.replace("edit_form", partial: 'notes/edit_form', locals: { note: @note }),
        turbo_stream.replace("spinner", partial: 'shared/spinner')
      ]
    end
  end

  def destroy
    if @note.destroy
      render turbo_stream: turbo_stream.remove(@note)
    end
  end

  def update_ranks
    params["ranks"].each do |id, rank|
      Note.find(id).update(rank: rank)
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body, :user_id)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_edit_form.html.erb
<%= form_with model: note, data: { note_target: 'editForm' } do |f| %>
  <div class="flex items-center justify-between mb-4">
    <h2 class="flex-1"><%= f.text_field :title, placeholder: "Your title", autofocus: !note.persisted?, data: {action: 'keyup->note#saveInput' }, class: 'text-2xl bg-transparent p-0 w-full border-none focus:ring-0' %></h2>
    <%= render 'shared/spinner' %>
  </div>

  <%= f.text_area :body, placeholder: "Start writing your note here...", data: {note_target: 'textArea', action: 'input->note#resizeTextArea keyup->note#saveInput' }, class: 'w-full bg-white border-none rounded-lg py-3 px-5 resize-none overflow-hidden focus:ring-0' %>
<% end %>

app/views/notes/_note.html.erb
<div id=<%= dom_id(note) %> class="group flex justify-between bg-white rounded-lg py-3 px-5 mb-2 cursor-grab active:cursor-grabbing" data-sortable-target="item">
  <%= link_to note_path(note) do %>
    <%= note.title %>
  <% end %>
  <%= button_to note_path(note), method: :delete, form: {data: {turbo_confirm: 'Are you sure ?'}}, class: 'hidden group-hover:block' do %>
    <i class="fa-solid fa-trash text-gray-600"></i>
  <% end %>
</div>

app/views/notes/_notes.html.erb
<%= turbo_frame_tag "notes" do %>
  <div data-controller="sortable" data-sortable-class-value="Note">
    <%= render partial: 'notes/note', collection: notes %>
  </div>
<% end %>

app/views/notes/new.html.erb
<%= render 'shared/back_home' %>

<div data-controller="note">
  <%= render partial: 'notes/edit_form', locals: { note: Note.new } %>
</div>

app/views/notes/show.html.erb
<%= render 'shared/back_home' %>

<div data-controller="note">
  <%= render partial: 'notes/edit_form', locals: { note: @note } %>
</div>