config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  
  resources :lists do
    delete '/clear_items', to: 'lists#clear_items'
    resources :items
  end
  
  resources :notes, only: [:index, :show, :new, :create, :update, :destroy]
  
  post '/update_ranks', to: 'ranking#update_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/rankable.rb
module Rankable
  extend ActiveSupport::Concern

  included do
    before_create :add_rank
    scope :ordered_by_rank, -> { order(rank: :asc) }
  end

  def add_rank
    user_items = self.class.where(user: user)
    self.rank = user_items.present? ? user_items.pluck(:rank).max + 1 : 1
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  
  attribute :done, default: false, inclusion: { in: [true, false] }
  validates :name, presence: { message: "Item cannot be blank" }, uniqueness: { scope: :list_id, message: "Item already exists" }

  scope :done, -> { where(done: true) }
  scope :not_done, -> { where(done: false) }
end

app/models/list.rb
class List < ApplicationRecord
  include Rankable

  has_many :items, dependent: :destroy
  belongs_to :user  
end

app/models/note.rb
class Note < ApplicationRecord
  include Rankable

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :notes
  has_many :lists

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Used to correctly redirect after oauth sign in
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || dashboard_path
  end

  def user_not_authorized
    redirect_back(fallback_location: root_path, allow_other_host: false)
    flash[:alert] = t 'errors.action_not_allowed'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:update, :destroy]
  before_action :set_items, only: [:index]

  def index
    render partial: 'items/items', locals: { items: @items }
  end

  def create
    item = Item.new(item_params)
    if item.save
      render turbo_stream: [
        turbo_stream.prepend(:items, partial: 'items/item', locals: { item: item }),
        turbo_stream.update(:items_count, Item.where(list: item.list).not_done.count),
        turbo_stream.replace('add-item-wrapper', partial: 'items/add_item_button', locals: { list: item.list })
      ]
    else
      render turbo_stream: turbo_stream.replace('item_form', partial: 'items/form', locals: { list: item.list, item: item })
    end
  end

  def update
    if @item.update(item_params)
      render turbo_stream: [
        turbo_stream.replace(helpers.dom_id(@item), partial: 'items/item', locals: { item: @item }),
        turbo_stream.update(:items_count, Item.where(list: @item.list).not_done.count)
      ]
    end
  end

  def destroy
    @item.destroy
  end

  private

  def item_params
    params.require(:item).permit(:name, :done, :list_id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_items
    @items = Item.where(list_id: params[:list_id]).order(created_at: :desc)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]
  before_action :authenticate_user!

  def index
    @lists = List.where(user: current_user).ordered_by_rank
    render partial: 'lists/lists', locals: { lists: @lists }
  end

  def show
    user_not_authorized if @list.user != current_user
  end

  def destroy
    if @list.destroy
      render turbo_stream: turbo_stream.remove(@list)
    end
  end

  def clear_items
    @list = List.find(params[:list_id])
    
    if @list.items.destroy_all
      render turbo_stream: [
        turbo_stream.replace(:items, partial: 'items/items', locals: { items: nil }),
        turbo_stream.update(:items_count, 0)
      ]
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  def index
    @notes = Note.where(user: current_user).ordered_by_rank
    render partial: 'notes/notes', locals: { notes: @notes }
  end

  def show
    user_not_authorized if @note.user != current_user
  end

  def new; end

  def create
    @note = Note.new(note_params)
    @note.user = current_user

    if @note.save
      redirect_to @note
    end
  end

  def update
    if @note.update(note_params)
      render turbo_stream: [
        turbo_stream.replace("edit_form", partial: 'notes/edit_form', locals: { note: @note }),
        turbo_stream.replace("spinner", partial: 'shared/spinner')
      ]
    end
  end

  def destroy
    if @note.destroy
      render turbo_stream: turbo_stream.remove(@note)
    end
  end

  def update_ranks
    params["ranks"].each do |id, rank|
      Note.find(id).update(rank: rank)
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home]

  def dashboard; end

  def home
    redirect_to dashboard_path if current_user # Home should only be available to unlogged users
    @home = true
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  def update_all
    klass = params["class"].constantize
    params["ranks"].each do |id, rank|
      klass.find(id).update(rank: rank + 1)
    end
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>EasyList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full	<%= @home ? 'bg-cyan-800' : 'bg-gray-100' %>">
    <%= render 'shared/flash' %>
  
    <div id="page-content" class="container mx-auto p-4 duration-150 transition">
      <%= render 'shared/navbar' %>

      <main>
        <%= yield %>
      </main>
    </div>

    <%= render 'shared/fab' unless @home %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<section class="mb-6">
  <h2 class="mb-4">My lists</h2>
  <%= turbo_frame_tag "lists", src: lists_path, loading: 'lazy', target: '_top' do %>
    <i class="fas fa-spinner fa-spin fa-2xl"></i>
    <span>Loading lists...</span>
  <% end %>
</section>

<section>
  <h2 class="mb-4">My notes</h2>
  <%= turbo_frame_tag "notes", src: notes_path, loading: 'lazy', target: '_top' do %>
    <i class="fas fa-spinner fa-spin fa-2xl"></i>
    <span>Loading lists...</span>
  <% end %>
</section>

app/views/pages/home.html.erb
<div class="py-24">
  <h1 class="text-4xl font-bold text-white text-center mb-4">EasyList</h1>
  <p class="text-white text-center">All your lists and notes in one place</p>
</div>

<% resource_class.omniauth_providers.each do |provider| %>
  <% break unless provider == :google_oauth2 %>
  <%= link_to omniauth_authorize_path(resource_name, provider), method: :post do %>
    <div class="mx-auto bg-gray-200 h-12 max-w-sm	rounded-md flex items-center justify-center">
      <%= image_tag 'google/g_logo.png', class: 'h-3/4 mr-3' %>
      <span class="font-medium">Sign in with Google</span>
    </div>
  <% end %>
<% end %>

<div class="max-w-sm my-3 mx-auto flex items-center before:content-[''] before:flex-1 before:border-b before:mr-3 after:content-[''] after:flex-1 after:border-b after:ml-3 text-white">Or</div>

<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'mx-auto max-w-sm' }) do |f| %>
  <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email", class: 'w-full rounded-md mb-2' %>
  <%= f.password_field :password, autocomplete: "current-password", placeholder: "Password", class: 'w-full rounded-md' %>

  <% if false && devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <%= f.submit "Sign in", class: 'w-full rounded-md bg-lemon-meringue h-12 mt-6 font-medium' %>
<% end %>

<div class="text-center text-white mt-4">Don't have an account? <%= link_to 'Sign up here', new_user_registration_path, class: 'text-lemon-meringue font-semibold' %></div>

app/views/shared/_avatar_small.html.erb
<div class="overflow-hidden relative w-10 h-10 bg-gray-100 rounded-full dark:bg-gray-600 cursor-pointer" data-action="click->nav#toggle">
  <% if current_user&.avatar_url %>
    <%# Using <img> to add referrerpolicy %>
    <img src=<%= current_user.avatar_url %> referrerpolicy="no-referrer">
  <% else %>
    <svg class="absolute -left-1 w-12 h-12 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
  <% end %>
</div>

app/views/shared/_back_home.html.erb
<%= link_to dashboard_path, class: 'block mb-3 text-gray-500' do %>
  <i class="fa-solid fa-chevron-left"></i> Home
<% end %>

app/views/shared/_fab.html.erb
<div data-controller="fab" class="fixed bottom-6 right-6 flex flex-col items-end">
  <div class="flex flex-col items-end transition-all overflow-hidden max-h-0 opacity-0" data-fab-target="newItemsButtons" data-action="click@window->fab#collapseIfOutsideClick">
    <div class="flex items-center mb-3 group">
      <span class="mr-3 md:group-hover:font-medium">New list</span>
      <div class="bg-blue-700 md:group-hover:bg-blue-800 rounded-full w-16 h-16 flex justify-center items-center">
        <span class="text-2xl text-white font-bold"><i class="fa-solid fa-list-check"></i></span>
      </div>  
    </div>
    <%= link_to new_note_path do %>
      <div class="flex items-center mb-3 group">
        <span class="mr-3 md:group-hover:font-medium">New note</span>
        <div class="bg-blue-700 md:group-hover:bg-blue-800 rounded-full w-16 h-16 flex justify-center items-center">
          <span class="text-2xl text-white font-bold"><i class="fa-solid fa-file-lines"></i></span>
        </div>  
      </div>
    <% end %>
  </div>
  <div class="flex justify-center items-center text-3xl font-semibold text-white bg-blue-700 shadow-lg shadow-gray-400 rounded-full w-16 h-16 transition-all cursor-pointer select-none" id="fab" data-fab-target="addButton" data-action="click->fab#toggle">
    <i class="fa-solid fa-plus"></i>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="fixed top-2 left-2/4 -translate-x-2/4 w-fit max-w-xs md:max-w-sm" data-controller="flash">
    <% flash.each do |type, msg| %>
      <div class="<%= type == 'notice' ? 'bg-green-200' : 'bg-yellow-200' %> relative flex items-center text-center py-2 px-4 rounded-lg transition-all duration-300 cursor-pointer" data-flash-target="message" data-action="click->flash#dismiss">
        <span class="flex-1"><%= msg %></span>
        <i class="fa-solid fa-circle-xmark ml-4"></i>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav data-controller="nav" class="flex justify-between">
  <h1 class="font-bold text-4xl mb-4">Easy List</h1>
  <div class="relative">
    <%= render 'shared/avatar_small' %>
    <div class="absolute right-0 hidden bg-white border mt-2 p-3 whitespace-nowrap" data-nav-target="menu">
      <ul>
        <%= link_to 'Edit account', edit_user_registration_path %>
        <%= button_to 'Logout', destroy_user_session_path, data: { turbo: false }, method: :delete %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_spinner.html.erb
<svg id="spinner" class="animate-spin fill-transparent h-5 w-5 mr-3 invisible" data-note-target="spinner" viewBox="0 0 24 24">
  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="grey" stroke-width="4"></circle>
  <path class="opacity-75" fill="black" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
</svg>