config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  
  resources :lists do
    delete '/clear_items', to: 'lists#clear_items'
    resources :items
  end
  
  resources :notes, only: [:index, :show, :new, :create, :update, :destroy]
  
  post '/update_ranks', to: 'ranking#update_all'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  
  attribute :done, default: false, inclusion: { in: [true, false] }
  validates :name, presence: { message: "Item cannot be blank" }, uniqueness: { scope: :list_id, message: "Item already exists" }

  scope :done, -> { where(done: true) }
  scope :not_done, -> { where(done: false) }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:update, :destroy]
  before_action :set_items, only: [:index]

  def index
    render partial: 'items/items', locals: { items: @items }
  end

  def create
    item = Item.new(item_params)
    if item.save
      render turbo_stream: [
        turbo_stream.prepend(:items, partial: 'items/item', locals: { item: item }),
        turbo_stream.update(:items_count, Item.where(list: item.list).not_done.count),
        turbo_stream.replace('add-item-wrapper', partial: 'items/add_item_button', locals: { list: item.list })
      ]
    else
      render turbo_stream: turbo_stream.replace('item_form', partial: 'items/form', locals: { list: item.list, item: item })
    end
  end

  def update
    if @item.update(item_params)
      render turbo_stream: [
        turbo_stream.replace(helpers.dom_id(@item), partial: 'items/item', locals: { item: @item }),
        turbo_stream.update(:items_count, Item.where(list: @item.list).not_done.count)
      ]
    end
  end

  def destroy
    @item.destroy
  end

  private

  def item_params
    params.require(:item).permit(:name, :done, :list_id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_items
    @items = Item.where(list_id: params[:list_id]).order(created_at: :desc)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_add_item_button.html.erb
<div data-controller="item" id="add-item-wrapper" class="inline-flex mb-5">
  <div data-item-target="addItemButton" data-action="click->item#showAddItemForm" class="bg-gray-200 rounded-lg px-5 py-3 border border-gray-300">
    + Add item
  </div>
  <div class="hidden" data-item-target="addItemForm">
    <%= render partial: 'items/form', locals: { list: list, item: Item.new } %>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with model: [list, item], id: "item_form", data: {action: "click@window->item#hideFormIfOutsideClick"} do |f| %>
  <div class="flex">
    <%= f.hidden_field :list_id, value: list.id %> 
    <%= f.text_field :name, data: { item_target: "input", action: "focus->item#hideFab blur->item#showFab input->item#removeErrors input->item#enableSubmit"}, class: "rounded-lg border-1 border-blue-700 #{'border-red-500 bg-red-100' if f.object.errors[:name].present?}" %>
    <%= f.submit "Add item", data: { item_target: "submitButton" }, disabled: true, class: 'rounded-lg bg-blue-700 md:hover:bg-blue-800 font-semibold text-white cursor-pointer px-3 disabled:opacity-25 disabled:cursor-not-allowed' %>
  </div>
  <p data-item-target="error" class="mt-2 text-sm text-red-600">
    <%= f.object.errors.messages_for(:name).first %>
  </p>
<% end %>

app/views/items/_item.html.erb
<div id=<%= dom_id(item) %> data-controller="item" class="group flex justify-between bg-white rounded-lg py-3 px-5 mb-2">
  <div class="flex">
    <%= form_with model: [item.list, item], data: { item_target: "form" } do |f| %>
      <%= f.check_box :done, {data: {item_target: "checkbox", action: "change->item#submitForm"}, class: 'w-6 h-6 rounded-full mr-3 cursor-pointer' }, 1, 0 %>
    <% end %>
    <span class="cursor-pointer	<%= 'line-through' if item.done %>" data-action="click->item#toggleCheckbox"><%= item.name %></span>
  </div>
  <%= button_to list_item_path(item.list, item), method: :delete, form: {data: {turbo_confirm: 'Are you sure ?'}}, class: 'hidden group-hover:block' do %>
    <i class="fa-solid fa-trash text-gray-600"></i>
  <% end %>
</div>

app/views/items/_items.html.erb
<%= turbo_frame_tag "items" do %>
  <%= render partial: 'items/item', collection: items %>
<% end %>

app/views/items/destroy.turbo_stream.erb
<%= turbo_stream.remove(@item) %>
<%= turbo_stream.update(:items_count, Item.not_done.count) %>